### ISSUE TITLE
module 'matplotlib.cbook' has no attribute '_make_class_factory'

### ISSUE THREAD

**Issue by tqwang743** [JiangBioLab/DeepST#5]
When i run the code`from deepst.DeepST import run`, The following error occurred
![image](https://user-images.githubusercontent.com/108932740/214586536-231b26fc-a16c-4006-848c-2f69f42ec0f5.png)

**Comment by JiangBioLab** [comment]
Thank you for using DeepST. We have updated the version of the dependent python packages, you can reinstall and hopefully it will solve your problem.
